services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "8002:8000"
    env_file:
      - .env
    volumes:
      - ./app:/app/app
    restart: unless-stopped
