"""init

Revision ID: de7e0d499299
Revises: 
Create Date: 2025-10-03 18:54:22.555009

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'de7e0d499299'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('years_experience', sa.Integer(), nullable=False),
    sa.Column('breed', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('salary', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('missions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('complete', sa.Boolean(), nullable=False),
    sa.Column('cat_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['cat_id'], ['cats.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('uq_active_mission_per_cat', 'missions', ['cat_id'], unique=True, postgresql_where=sa.text('cat_id IS NOT NULL AND complete = false'))
    op.create_table('targets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mission_id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('country', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('notes', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('complete', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['mission_id'], ['missions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('mission_id', 'name', name='uq_target_name_per_mission')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('targets')
    op.drop_index('uq_active_mission_per_cat', table_name='missions', postgresql_where=sa.text('cat_id IS NOT NULL AND complete = false'))
    op.drop_table('missions')
    op.drop_table('cats')
    # ### end Alembic commands ###
